name: pix_multi_final
description: Gerador de QR Code PIX Profissional
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'  
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.2.0
  crypto: ^3.0.3
  image_picker: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
