name: Build Windows
on:
  push:
    tags:
      - 'v*'
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows --release
      - name: Create ZIP
        shell: pwsh
        run: Compress-Archive -Path build/windows/runner/Release/* -DestinationPath pix_multi_final_windows.zip
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: pix_multi_final_windows.zip
